// ---------------------------------------------------------------------------
// Groq adapter — kept only as a failover for when Gemini is unreachable.
//
// This was the primary provider until 2026-09-09. It was replaced because
// `qwen/qwen3.6-27b` misidentified the photographed object in 2 of 18 measured
// scans (Gemini Flash-Lite: 0 of 90), and because both of Groq's vision models
// are Preview status — "not recommended for production, may be discontinued at
// short notice" — with no production vision model behind them.
//
// It stays wired up because a card generated by a weaker model beats a scan
// that fails outright, and the key already exists. It is a lifeboat, not a
// second engine: it has no structured-output support, so `responseSchema` is
// ignored here and correctness rests on the prose schema in the prompt.
// Set LLM_FALLBACK=off to drop it.
//
// Its rate limits are unusual and worth remembering: the free tier caps
// **tokens per day** (200k app-wide, ~37 scans), and that limit appears in NO
// response header — only inside the body of a 429. Hence parseRateLimit below.
// ---------------------------------------------------------------------------

import {
  type LlmProvider,
  type LlmRequest,
  type LlmResult,
  type Transport,
  LlmError,
  cleanJsonResponse,
} from './types.ts';

const ENDPOINT = 'https://api.groq.com/openai/v1/chat/completions';

export interface GroqOptions {
  apiKey?: string;
  model?: string;
  transport?: Transport;
}

/** Pulls a wait hint, and notes whether this is the daily wall or a short dip. */
function parseRateLimit(response: Response, bodyText: string): { retryAfterMs: number; daily: boolean } {
  const daily = /tokens per day|TPD/i.test(bodyText);

  const header = response.headers.get('retry-after');
  if (header) {
    const seconds = Number(header);
    if (Number.isFinite(seconds)) return { retryAfterMs: seconds * 1000, daily };
  }
  const match = bodyText.match(/try again in ([\d.]+)s/i);
  if (match) return { retryAfterMs: parseFloat(match[1]) * 1000, daily };
  return { retryAfterMs: 2000, daily };
}

export function createGroqProvider(options: GroqOptions = {}): LlmProvider {
  const model = options.model ?? 'qwen/qwen3.6-27b';
  const transport = options.transport ?? fetch;
  const resolveKey = () => options.apiKey ?? Deno.env.get('GROQ_API_KEY') ?? '';

  return {
    name: 'groq',
    model,
    isConfigured: () => resolveKey().length > 0,

    async send(request: LlmRequest): Promise<LlmResult> {
      const apiKey = resolveKey();
      if (!apiKey) throw new LlmError('auth', 'groq', 'GROQ_API_KEY not set');

      const content = request.parts.map((part) =>
        part.kind === 'text'
          ? { type: 'text', text: part.text }
          : { type: 'image_url', image_url: { url: `data:${part.mimeType};base64,${part.data}` } },
      );

      let response: Response;
      try {
        response = await transport(ENDPOINT, {
          method: 'POST',
          headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({
            model,
            messages: [{ role: 'user', content }],
            temperature: request.temperature,
            max_completion_tokens: request.maxOutputTokens,
            // Qwen reasons by default and prepends a <think> block; these keep
            // the content field pure JSON.
            reasoning_effort: 'none',
            reasoning_format: 'hidden',
          }),
        });
      } catch (cause) {
        throw new LlmError('timeout', 'groq', 'network error calling Groq', { cause });
      }

      if (!response.ok) {
        const bodyText = await response.text().catch(() => '');
        if (response.status === 429) {
          const { retryAfterMs, daily } = parseRateLimit(response, bodyText);
          throw new LlmError(
            'rate_limit',
            'groq',
            daily ? 'Groq daily token budget exhausted' : 'Groq rate limit',
            // A spent daily budget will not refill inside a retry loop; report
            // no wait hint so the chain fails over instead of sleeping.
            { status: 429, retryAfterMs: daily ? undefined : retryAfterMs },
          );
        }
        if (response.status === 401 || response.status === 403) {
          throw new LlmError('auth', 'groq', bodyText.slice(0, 200), { status: response.status });
        }
        if (response.status >= 500) {
          throw new LlmError('unavailable', 'groq', bodyText.slice(0, 200), { status: response.status });
        }
        throw new LlmError('invalid', 'groq', bodyText.slice(0, 200), { status: response.status });
      }

      const payload = await response.json().catch(() => ({}));
      const text = payload?.choices?.[0]?.message?.content;
      if (!text) throw new LlmError('empty', 'groq', 'no content in Groq response', { status: 200 });

      const usage = payload?.usage ?? {};
      return {
        text: cleanJsonResponse(text),
        usage: {
          promptTokens: usage.prompt_tokens ?? 0,
          outputTokens: usage.completion_tokens ?? 0,
        },
        provider: 'groq',
        model,
      };
    },
  };
}
